### PR TITLE
Added functions to run scripts without -e parameter

### PR DESCRIPTION
**Pull request by AngryKiller**
Useful for support with scripts using libs like [applescript-json](https://github.com/mgax/applescript-json).

### CODE REVIEW

**Comment by sindresorhus** [comment]
How would you use this new API? It's not clear how it solves the problem?

**Comment by AngryKiller** [comment]
```applescript-json``` needs to be compiled to run correctly, if you just execute the code, there will be errors.

**Comment by sindresorhus** [comment]
That is contradictive to its readme:

> Alternatively, just copy/paste the contents of json.applescript into your own script, and use it straight away.

**Comment by AngryKiller** [comment]
Yeah, but then, if you run your script with the content of json.applescript pasted with the -e parameter, you will get errors and it will not work ;)

**Comment by AngryKiller** [comment]
Oh, and it can also be used to run scripts that are already compiled.

**Comment by AngryKiller** [comment]
Hi, do you need anything else to merge?

**Comment by sindresorhus** [comment]
Ok, I understand now. I was confused by your incorrect use of parameter names. Without `-e` it's actually a file path, not a script. The methods should be named `.file()` and `.fileSync()` and needs some tests too.

**Pull request closed without merging**
